---
openapi: 3.0.3
info:
  title: api
  version: 1.0.0
servers: []
paths:
  "/auth/register":
    post:
      summary: create new user
      tags:
      - Authentication
      parameters:
      - name: email
        in: query
        required: false
        schema:
          type: string
        example: nomads@nomads.com
      - name: headers[Content-type]
        in: query
        required: false
        schema:
          type: object
          properties:
            Content-type:
              type: string
          required:
          - Content-type
        example:
          Content-type: application/json
      - name: password
        in: query
        required: false
        schema:
          type: string
        example: nomads
      - name: username
        in: query
        required: false
        schema:
          type: string
        example: nomads
      responses:
        '201':
          description: create new user with uniq email; return created user or error;
            return jwt auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                      password_digest:
                        type: string
                      age:
                        nullable: true
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      jti:
                        type: string
                    required:
                    - id
                    - username
                    - email
                    - password_digest
                    - age
                    - created_at
                    - updated_at
                    - jti
                  token:
                    type: string
                required:
                - message
                - user
                - token
              example:
                message: User created successfully
                user:
                  id: 4
                  username: nomads
                  email: nomads@nomads.com
                  password_digest: "$2a$04$ZONTh7M2TUwoYxw83TUKH.Ra.OTRQ2VZOhGTisEJhq0kpKoAHs/DS"
                  age: 
                  created_at: '2023-10-31T19:50:23.046Z'
                  updated_at: '2023-10-31T19:50:23.046Z'
                  jti: c596b5f4-2b27-4efc-beaa-77ef28d775b6
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2OTkzODY2MjN9.CZRDyA5vbG-HRng6F3f4L3lowULygRZplRTFMV8n1fI
        '409':
          description: create new user with uniq email; return created user or error;
            return jwt auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: email already exists
  "/":
    get:
      summary: index
      tags:
      - Doc
      responses:
        '200':
          description: returns api documentaion
          content:
            text/html:
              schema:
                type: string
              example: |
                <!DOCTYPE html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <meta
                      name="description"
                      content="SwaggerUI"
                    />
                    <title>SwaggerUI</title>
                    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui.css" />
                  </head>
                  <body>
                  <div id="swagger-ui"></div>
                  <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-bundle.js" crossorigin></script>
                  <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-standalone-preset.js" crossorigin></script>
                  <script>
                    window.onload = () => {
                      window.ui = SwaggerUIBundle({
                        url: 'openapi.yaml',
                        dom_id: '#swagger-ui',
                        presets: [
                          SwaggerUIBundle.presets.apis,
                          SwaggerUIStandalonePreset
                        ],
                        layout: "StandaloneLayout",
                      });
                    };
                  </script>
                  </body>
                </html>
  "/auth/login":
    post:
      summary: login as user
      tags:
      - Authentication
      parameters:
      - name: email
        in: query
        required: false
        schema:
          type: string
        example: nomads@nomads.com
      - name: headers[Content-type]
        in: query
        required: false
        schema:
          type: object
          properties:
            Content-type:
              type: string
          required:
          - Content-type
        example:
          Content-type: application/json
      - name: password
        in: query
        required: false
        schema:
          type: string
        example: nomads
      responses:
        '200':
          description: login as existing user by email
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                      password_digest:
                        type: string
                      age:
                        type: integer
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      jti:
                        type: string
                    required:
                    - id
                    - username
                    - email
                    - password_digest
                    - age
                    - created_at
                    - updated_at
                    - jti
                  token:
                    type: string
                required:
                - user
                - token
              example:
                user:
                  id: 3
                  username: nomads
                  email: nomads@nomads.com
                  password_digest: "$2a$04$Hkd9r64dKpn1Y3FjQSY0Yug93oU96p26AXDo1TnX5tjFYn.emqTa."
                  age: 3
                  created_at: '2023-10-31T19:50:23.015Z'
                  updated_at: '2023-10-31T19:50:23.015Z'
                  jti: edd17644-15b2-4473-9d88-d9e2423b0840
                token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2OTkzODY2MjN9.2hLMK7WjTt0mNZSG4cHemvYMjFKSH4JG3M20JHX3gc0
  "/api/v1/authors":
    get:
      summary: list all authors
      tags:
      - Api::V1::Author
      parameters:
      - name: headers[Authorization]
        in: query
        required: false
        schema:
          type: object
          properties:
            Authorization:
              type: string
          required:
          - Authorization
        example:
          Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2OTkzODY2MjJ9.gy0BzeLOIPNw2b8MFrTZb63HQChXtFzzj6AoCCVnPJM
      responses:
        '200':
          description: list all authors ordered by default
          content:
            application/vnd.api+json:
              schema:
                type: string
              example: '{"data":[{"id":"2","type":"authors","links":{"self":"http://www.example.com/api/v1/authors/2"},"attributes":{"username":"nomads"}}]}'
  "/api/v1/users":
    get:
      summary: list all users
      tags:
      - Api::V1::User
      responses:
        '401':
          description: list all users ordered by default
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unauthorized
      parameters:
      - name: headers[Authorization]
        in: query
        required: false
        schema:
          type: object
          properties:
            Authorization:
              type: string
          required:
          - Authorization
        example:
          Authorization: bearer `12345`
  "/api/v1/users/{user_id}/relationships/roles":
    post:
      summary: roles
      tags:
      - Api::V1::User
      parameters:
      - name: relationship
        in: path
        required: true
        schema:
          type: string
        example: roles
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
        example: 7
      responses:
        '422':
          description: crud roles
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Role 100500 does not exists
        '201':
          description: crud roles
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
              example:
                message: UserRole created successfully
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                role_id:
                  type: string
              required:
              - role_id
            example:
              role_id: '100500'
  "/api/v1/roles":
    get:
      summary: roles
      tags:
      - Api::V1::Role
      responses:
        '200':
          description: crud roles
          content:
            application/vnd.api+json:
              schema:
                type: string
              example: '{"data":[{"id":"9","type":"roles","links":{"self":"http://www.example.com/api/v1/roles/9"},"attributes":{"name":"author"},"relationships":{"user-role":{"links":{"self":"http://www.example.com/api/v1/roles/9/relationships/user-role","related":"http://www.example.com/api/v1/roles/9/user-role"}},"users":{"links":{"self":"http://www.example.com/api/v1/roles/9/relationships/users","related":"http://www.example.com/api/v1/roles/9/users"}}}}]}'
    post:
      summary: roles
      tags:
      - Api::V1::Role
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                      - name
                  required:
                  - type
                  - attributes
              required:
              - data
            example:
              data:
                type: roles
                attributes:
                  name: test
      responses:
        '201':
          description: crud roles
          content:
            application/vnd.api+json:
              schema:
                type: string
              example: '{"data":{"id":"8","type":"roles","links":{"self":"http://www.example.com/api/v1/roles/8"},"attributes":{"name":"test"},"relationships":{"user-role":{"links":{"self":"http://www.example.com/api/v1/roles/8/relationships/user-role","related":"http://www.example.com/api/v1/roles/8/user-role"}},"users":{"links":{"self":"http://www.example.com/api/v1/roles/8/relationships/users","related":"http://www.example.com/api/v1/roles/8/users"}}}}}'
  "/api/v1/roles/{id}":
    delete:
      summary: roles
      tags:
      - Api::V1::Role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 10
      responses:
        '204':
          description: crud roles
          content:
            '':
              schema:
                type: string
              example: ''
